; asmsyntax=fasm

public ISR_0
public ISR_1 
public ISR_2 
public ISR_3 
public ISR_4 
public ISR_5 
public ISR_6 
public ISR_7 
public ISR_8 
public ISR_9 
public ISR_10 
public ISR_11 
public ISR_12 
public ISR_13 
public ISR_14 
public ISR_15 
public ISR_16 
public ISR_17 
public ISR_18 
public ISR_19 
public ISR_20 
public ISR_21 
public ISR_22 
public ISR_23 
public ISR_24 
public ISR_25 
public ISR_26 
public ISR_27 
public ISR_28 
public ISR_29 
public ISR_30 
public ISR_31

ISR_0:
	jmp ISRCommonStub

ISR_1:
	jmp ISRCommonStub

ISR_2:
	jmp ISRCommonStub

ISR_3:
	jmp ISRCommonStub

ISR_4:
	jmp ISRCommonStub

ISR_5:
	jmp ISRCommonStub

ISR_6:
	jmp ISRCommonStub

ISR_7:
	jmp ISRCommonStub

ISR_8:
	jmp ISRCommonStub

ISR_9:
	jmp ISRCommonStub

ISR_10:
	jmp ISRCommonStub

ISR_11:
	jmp ISRCommonStub

ISR_12:
	jmp ISRCommonStub

ISR_13:
	jmp ISRCommonStub

ISR_14:
	jmp ISRCommonStub

ISR_15:
	jmp ISRCommonStub

ISR_16:
	jmp ISRCommonStub

ISR_17:
	jmp ISRCommonStub

ISR_18:
	jmp ISRCommonStub

ISR_19:
	jmp ISRCommonStub

ISR_20:
	jmp ISRCommonStub

ISR_21:
	jmp ISRCommonStub

ISR_22:
	jmp ISRCommonStub

ISR_23:
	jmp ISRCommonStub

ISR_24:
	jmp ISRCommonStub

ISR_25:
	jmp ISRCommonStub

ISR_26:
	jmp ISRCommonStub

ISR_27:
	jmp ISRCommonStub

ISR_28:
	jmp ISRCommonStub

ISR_29:
	jmp ISRCommonStub

ISR_30:
	jmp ISRCommonStub

ISR_31:
	jmp ISRCommonStub
